# '''Write a program to take a single character as input and check whether it is an uppercase letter or a lowercase letter.'''

# character=input("Enter a character:")
# if(len(character)==1):
#     if character.islower():

#         print("LOWERCASE")

#     elif character.isupper():
    
#         print("UPPERCASE")
#     else:
#         print("Not a alphabet")

# else:
#     print("Invalid character")
a=input("ENTER:")
a.islower()
print(a.islower())